# Generated by Django 6.0.6 on 2026-06-28 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_favoriteproduct_favoriteworker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.CreateModel(
            name='ProductReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_phone', models.CharField(max_length=15)),
                ('reason', models.CharField(choices=[('fake', 'Fake Product'), ('wrong_info', 'Wrong Information'), ('spam', 'Spam'), ('scam', 'Scam'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='services.product')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_phone', models.CharField(max_length=15)),
                ('reason', models.CharField(choices=[('fake', 'Fake Profile'), ('wrong_contact', 'Wrong Contact'), ('bad_behavior', 'Bad Behavior'), ('spam', 'Spam'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='services.workerprofile')),
            ],
        ),
    ]
